import matplotlib.pyplot as plt

plt.plot([-9, -8], [7, 7], color="black")
plt.plot([-9, -8], [5, 5], color="black")
plt.plot([-9, -8], [2, 4], color="black")
plt.plot([-7, -7], [2, 7], color="black")
plt.plot([-3, -7], [7, 7], color="blacK")
plt.plot([-5, -6], [6, 6], color="black")
plt.plot([-6, -6], [4, 5], color="black")
plt.plot([-5, -6], [5, 5], color="black")
plt.plot([-5, -5], [4, 5], color="black")
plt.plot([-5, -6], [4, 4], color="black")

plt.plot([-3, -4], [2, 8], color="blacK")
plt.plot([-3, -5], [4, 2], color="black")
plt.plot([-2, -3], [8, 9], color="black")
plt.plot([2, 2], [4, 8], color="black")
plt.plot([-1, 0], [5, 7], color="black")
plt.plot([4, 5], [7, 5], color="black")
plt.plot([0, 3], [2, 5], color="black")
plt.plot([7, 9], [6, 6], color="black")
plt.plot([8, 8], [5, 7], color="black")
plt.plot([8, 9], [5, 3], color="black")

plt.plot([7, 10], [2, 5], color="black")
plt.plot([7, 10], [2, 2], color="black")
plt.plot([-8, -8], [23. / -3, -2], color="black")
plt.plot([-6, -8], [-2, -2], color="black")
plt.plot([-6, -6], [-2, -7], color="black")
plt.plot([-6, -8], [-4, -4], color="black")
plt.plot([-6, -8], [-6, -6], color="black")
plt.plot([-6, -9], [-7, -8], color="black")
plt.plot([-2, -5], [-3, -3], color="black")
plt.plot([-2, -2], [-3, -8], color="black")

plt.plot([-5, -4], [-8, -2], color="black")
plt.plot([0, 0], [-4, -7], color="black")
plt.plot([1, 4], [-4, -4], color="black")
plt.plot([3, 3], [-3, -8], color="black")
plt.plot([8, 10], [-2, -2], color="black")
plt.plot([7, 10], [-4, -2], color="black")
plt.plot([7, 11], [-4, -4], color="black")
plt.plot([9, 11], [-8, -4], color="black")
plt.plot([7, 9], [-8, -8], color="black")
plt.plot([7, 7], [-6, -8], color="black")
plt.plot([7, 10], [-6, -6], color="black")

plt.savefig("output.png")
